let myJokes = [
  {
    category: "Programming",
    type: "twopart",
    setup:
      "So what's a set of predefined steps the government might take to preserve the environment?",
    delivery: "An Al-Gore-ithm.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 52,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "What's the object-oriented way to become wealthy?",
    delivery: "Inheritance.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 46,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why do programmers wear glasses?",
    delivery: "Because they need to C#",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 50,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why did the database administrator leave his wife?",
    delivery: "She had one-to-many relationships.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 265,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "why do python programmers wear glasses?",
    delivery: "Because they can't C.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 294,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why did the web developer walk out of a resturant in disgust?",
    delivery: "The seating was laid out in tables.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 6,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "How do you generate a random string?",
    delivery: "Put a Windows user in front of Vim and tell them to exit.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 127,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why do Java programmers hate communism?",
    delivery: "They don't want to live in a classless society.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 53,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "What is the best prefix for global variables?",
    delivery: "//",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 32,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Genders are a lot like booleans.",
    delivery: "There's only two of them.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: true,
      explicit: false,
    },
    id: 47,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: ".NET developers are picky when it comes to food.",
    delivery: "They only like chicken NuGet.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 49,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup:
      "So what's a set of predefined steps the government might take to preserve the environment?",
    delivery: "An Al-Gore-ithm.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 52,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "why do python programmers wear glasses?",
    delivery: "Because they can't C.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 294,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "What is the most used language in programming?",
    delivery: "Profanity.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 193,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why did the Python data scientist get arrested at customs?",
    delivery: "She was caught trying to import pandas!",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 234,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Hey baby I wish your name was asynchronous...",
    delivery: "... so you'd give me a callback.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 54,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why did the functional programmer get thrown out of school?",
    delivery: "Because he refused to take classes.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 48,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup:
      "What do you get if you lock a monkey in a room with a typewriter for 8 hours?",
    delivery: "A regular expression.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 26,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "How did you make your friend rage?",
    delivery: "I implemented a greek question mark in his JavaScript code.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 147,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "What do you call a developer who doesn't comment code?",
    delivery: "A developer.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 14,
    safe: true,
    lang: "en",
  },
];

// console.log(myJokes.length);
let index = Math.floor(Math.random() * (myJokes.length - 1));
joke.innerHTML = myJokes[index].setup ;
joke1.innerHTML = myJokes[index].delivery;